title: Yiyang Li
position: Master Student
affiliation: Shanghai Jiao Tong University
email: eric-lee@sjtu.edu.cn

plugins:
  - jekyll-spaceship
  - jekyll-last-modified-at
  - jekyll-analytics

keywords: minimal academic
description:
  Master student [BCMI@SJTU](https://bcmi.sjtu.edu.cn/), Shanghai Jiao Tong University
canonical: https://ericlee8.github.io/

semantic_scholar: https://www.semanticscholar.org/author/Yiyang-Li/2110418724
google_scholar: https://scholar.google.com/citations?user=Q_Wj8HgAAAAJ
github_link: https://github.com/EricLee8

avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

jekyll_analytics:
  GoogleAnalytics:
    id: UA-249984993-1

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
